# Generated by Django 2.2.6 on 2020-02-21 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_remove_billingaddress_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cart.BillingAddress'),
        ),
    ]
