# Generated by Django 2.2.6 on 2020-01-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200131_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='once_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='strip_customer_id',
        ),
    ]
