# Generated by Django 2.2.6 on 2019-12-04 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_categorey'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorey',
            name='CATDes',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
