# Generated by Django 2.2.6 on 2020-02-21 23:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20200222_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=100)),
                ('shipping_address2', models.CharField(max_length=100)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('shipping_zip', models.CharField(max_length=100)),
                ('billing_address', models.CharField(max_length=100)),
                ('billing_address2', models.CharField(max_length=100)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('billing_zip', models.CharField(max_length=10)),
                ('same_billing_address', models.BooleanField(default=False)),
                ('set_default_shipping', models.BooleanField(default=False)),
                ('use_default_shipping', models.BooleanField(default=False)),
                ('set_default_billing', models.BooleanField(default=False)),
                ('save_info', models.BooleanField(default=False)),
            ],
        ),
    ]
