# Generated by Django 2.2.6 on 2020-02-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200131_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='once_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
    ]
