# Generated by Django 2.2.6 on 2020-02-22 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_option',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='use_default_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
