# Generated by Django 2.2.6 on 2020-01-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191205_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATLabel',
            field=models.CharField(choices=[('BR', 'badge red'), ('BB', 'badge blue'), ('BG', 'badge green')], default='now', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='PRDCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='DiscountPrice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='PRDIImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISNew',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISSeller',
            field=models.BooleanField(default=False, verbose_name='Best seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='Product URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(choices=[('lap', 'laptop'), ('TV', 'TV'), ('M', 'Mobile')], max_length=50, verbose_name='Name'),
        ),
    ]
