# Generated by Django 2.2.6 on 2020-02-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_auto_20200224_0212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
