# Generated by Django 2.2.6 on 2020-02-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_delete_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='default',
        ),
    ]
